<a href="https://colab.research.google.com/github/stewartjollymore/NLP_CourseUCSD/blob/main/NN_Homework6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import tensorflow as tf
import keras as ks
import pandas as pd

Problem #1

In [10]:
x = tf.constant([0.1, 0.2])

w1 = tf.constant([0.15, 0.05])
w2 = tf.constant([0.36])

bias = tf.constant([0.33, 0.56])

z1 = np.dot(x,w1)+bias[0]


In [56]:
a1_linear = tf.keras.activations.linear(z1)
z2 = np.dot(a1_linear,w2)+bias[1]
a2_linear = tf.keras.activations.linear(z2)
activations = pd.DataFrame([["linear", a1_linear.numpy(), a2_linear.numpy()[0]]], columns = ["Activation Function","a1","a2"])

a1_tanh = tf.keras.activations.tanh(z1)
z2 = np.dot(a1_tanh,w2)+bias[1]
a2_tanh = tf.keras.activations.tanh(z2)

activations = activations.append(pd.DataFrame([["Tanh", a1_tanh.numpy(), a2_tanh.numpy()[0]]], columns = ["Activation Function","a1","a2"]))

a1_relu = tf.keras.activations.relu(z1)
z2 = np.dot(a1_relu,w2)+bias[1]
a2_relu = tf.keras.activations.relu(z2)

activations = activations.append(pd.DataFrame([["Relu", a1_relu.numpy(), a2_relu.numpy()[0]]], columns = ["Activation Function","a1","a2"]))
activations


<ipython-input-56-15287e1f772f>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  activations = activations.append(pd.DataFrame([["Tanh", a1_tanh.numpy(), a2_tanh.numpy()[0]]], columns = ["Activation Function","a1","a2"]))
<ipython-input-56-15287e1f772f>:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  activations = activations.append(pd.DataFrame([["Relu", a1_relu.numpy(), a2_relu.numpy()[0]]], columns = ["Activation Function","a1","a2"]))


Activation Function        a1        a2
0              linear  0.355000  0.687800
0                Tanh  0.340802  0.593265
0                Relu  0.355000  0.687800

Problem #2

In [88]:
x = tf.constant([-4.0, 0.5, 4])

sig_grad = tf.keras.activations.sigmoid(x).numpy()*(1-tf.keras.activations.sigmoid(x).numpy())
tanh_grad = 1-(tf.keras.activations.tanh(x).numpy()*tf.keras.activations.tanh(x).numpy())
relu_grad = []
for i in range(len(x)):
  if (x.numpy()[i]<0):
    relu_grad.append(0)
  else:
    relu_grad.append(1)


print("Gradient of Sigmoid at X", sig_grad)
print()
print("Gradient of Tanh at X", tanh_grad)
print()
print("Gradient of Relu at X", relu_grad)

Gradient of Sigmoid at X [0.01766271 0.23500371 0.01766273]

Gradient of Tanh at X [0.0013411 0.7864477 0.0013411]

Gradient of Relu at X [0, 1, 1]


Problem #3

In [94]:
v1 = tf.constant([2.3, 1.2, 0.3, 0])
v2 = tf.constant([1.9, 1.7, 2.6, 0.2, 1.3])

print(tf.nn.softmax(v1).numpy())
print(tf.nn.softmax(v2).numpy())

[0.6375659  0.21222727 0.08628516 0.06392162]
[0.21910708 0.17938972 0.44122744 0.04002725 0.12024851]


Problem #4

In [139]:
bce = tf.keras.losses.BinaryCrossentropy(from_logits=False)

data = pd.DataFrame([[0,0.95], [0,0.8], [0,0.6], [0,0.4], [0,0.1],
                    [1,0.95], [1,0.8], [1,0.6], [1,0.4], [1,0.1]],
                    columns = ["Observed", "Computed"])

cost = []
for i in range(len(data)):
  cost.append(-1*((data["Observed"][i]*np.log(data["Computed"][i]))+(1-data["Observed"][i])*(np.log(1-data["Computed"][i]))))

data["Cost"] = cost
data

Observed  Computed      Cost
0         0      0.95  2.995732
1         0      0.80  1.609438
2         0      0.60  0.916291
3         0      0.40  0.510826
4         0      0.10  0.105361
5         1      0.95  0.051293
6         1      0.80  0.223144
7         1      0.60  0.510826
8         1      0.40  0.916291
9         1      0.10  2.302585

Problem #5

In [141]:
a = tf.constant([[5,2,3],[26,56,92],[3,0,26]])

a1 = tf.argmax(a, axis=0)
a2 = tf.argmax(a, axis=1)

print(a1.numpy())
print(a2.numpy())

[1 1 1]
[0 2 2]


Problem #6

In [173]:
w1 = tf.constant([[-4.0,-6.0,-5.0],[3.0,6.0,4.0]])
b1 = tf.constant([-2.0,3.0,-2.0])

w2 = tf.constant([[5.0],[-9.0],[7.0]])
b2 = tf.constant(4.0)

data = tf.constant([[0.0,0.0],
                 [1.0,0.0],
                 [0.0,1.0],
                 [1.0,1.0]])

targets = tf.constant([0.0,1.0,1.0,0.0])

In [186]:
layer1 = tf.sigmoid(tf.cast(tf.matmul(data, w1) + b1, tf.float32))

layer2 = tf.sigmoid(tf.cast(tf.matmul(layer1, w2) + b2, tf.float32))

model = pd.DataFrame(data.numpy(),
                     columns = ["input 1","input 2"])
model["target"] = targets.numpy()
model["pred"] = layer2.numpy()
model["error"] = (model["target"]-model["pred"])**2
model

input 1  input 2  target      pred     error
0      0.0      0.0     0.0  0.041379  0.001712
1      1.0      0.0     1.0  0.973193  0.000719
2      0.0      1.0     1.0  0.992014  0.000064
3      1.0      1.0     0.0  0.017915  0.000321